[package]
name = "battle-logic"
version = "0.1.0"
authors = ["yopox <yopoxdev@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.8"
pest_derive = "2.8"
pest-test = "0.1.6"
lazy_static = "1.5.0"
